const DATABASE_CDR_TYPE = "CDR";
const DATABASE_AUTH_TYPE = "AUTH";

module.exports.DATABASE_AUTH_TYPE = DATABASE_AUTH_TYPE;
module.exports.DATABASE_CDR_TYPE = DATABASE_CDR_TYPE;

const LIMITER_ENTER_TYPE = "ENTER";
const LIMITER_LEAVE_TYPE = "LEAVE";
const LIMITER_MAX_COUNT = 100;

module.exports.LIMITER_ENTER_TYPE = LIMITER_ENTER_TYPE;
module.exports.LIMITER_LEAVE_TYPE = LIMITER_LEAVE_TYPE;
module.exports.LIMITER_MAX_COUNT = LIMITER_MAX_COUNT;
